; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;todo fix X positio in text editor fix audio qualty fix GB save not all the time


[env:esp32-s3-devkitm-1]
platform = espressif32
board = m5stack-stamps3
framework = arduino
;espressif32 @ 6.12.0 
;board_build.flash_mode = qio

monitor_speed = 115200
upload_speed = 921600
;build_flags = 
;	-D ARDUINO_USB_CDC_ON_BOOT=1
;	-D ARDUINO_USB_MODE=1
	;-D LGFX_USE_V1
	;-D CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=1


    ;-D PIO_FRAMEWORK_ARDUINO_ENABLE_PS

;CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=y
; Flash write type
;board_build.flash_mode = qio

;  cpy – 270MHz
;board_build.f_cpu = 270000000L


;monitor_filters = esp32_exception_decoder, colorize


lib_deps = 
	bodmer/JPEGDecoder@^2.0.0
	bitbank2/AnimatedGIF@^2.2.0
	earlephilhower/ESP8266Audio@2.2.0
;board_build.filesystem = littlefs







build_flags =
    ;-std=c++17
    -D COMPILE_WIFI_THINGS
	;-D CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=1
	-D NEW_VERSION_GAMES ; it's work only on standalone not if run on launcher
    ;-D DISABLE_WATCHDOGS         ; cancel watchdog

;board_build.partitions = partitions_5m_spiffs_8mb.csv
;board_build.partitions = AdvanceOS_3_partition.csv
board_build.partitions = AdvanceOS.csv


