#include <Arduino.h>


// Generated by   : UTFTConverter v0.1
// Generated from : AdvanceOS_LOGO.png
// Time generated : 2026-01-07 20:38:31.1351184 UTC
// Image Size     : 240x135 pixels
// Memory usage   : 64800 bytes

// the actual image data in MyOS.cpp end of the file to save space
extern const unsigned short AdvanceOS_LOGO[32400];
